# Comment to disable encoder
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
# to use mouse mappings in the keymap
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_USB=y
# led-module settings
#CONFIG_ZMK_HID_INDICATORS=y
#CONFIG_PWM=y

#debugging settings
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_RESET_ON_FATAL_EXCEPTION=n